---
interface:
  # server
  - name: ethernet-1/1
    admin-state: enable
    mtu: 8932
    vlan-tagging: true
    subinterface:
      - index: 0
        type: bridged
        admin-state: enable
        vlan:
          encap:
            untagged: {}
  # spine
  - name: ethernet-1/49
    admin-state: enable
    mtu: 8982
    subinterface:
      - index: 0
        ip-mtu: 8968
        ipv4:
          admin-state: enable
          address:
            - ip-prefix: 192.168.12.1/30
  # loopback
  - name: system0
    admin-state: enable
    subinterface:
      - index: 0
        ipv4:
          admin-state: enable
          address:
            - ip-prefix: 10.0.0.2/32
  # anycastgw
  - name: irb1
    admin-state: enable
    subinterface:
      - index: 0
        admin-state: enable
        ip-mtu: 8968
        ipv4:
          admin-state: enable
          address:
            - ip-prefix: 192.168.0.254/24
              anycast-gw: true
          arp:
            learn-unsolicited: true
            host-route:
              populate:
                - route-type: static
                - route-type: dynamic
            evpn:
              advertise:
                - route-type: dynamic
        anycast-gw:
          virtual-router-id: 1

tunnel-interface:
  - name: vxlan1
    vxlan-interface:
      - index: 1
        type: bridged
        ingress:
          vni: 1
      - index: 10000
        type: routed
        ingress:
          vni: 10000
        egress:
          source-ip: use-system-ipv4-address

routing-policy:
  policy:
    - name: all
      default-action:
        policy-result: accept

network-instance:
  - name: default
    interface:
      - name: ethernet-1/49.0
      - name: system0.0
    protocols:
      bgp:
        autonomous-system: 102
        router-id: 10.0.0.2
        afi-safi:
          - afi-safi-name: ipv4-unicast
            admin-state: enable
        group:
          - group-name: eBGP-underlay
            export-policy: all
            import-policy: all
            peer-as: 201
            afi-safi:
              - afi-safi-name: ipv4-unicast
                admin-state: enable
          - group-name: iBGP-overlay
            export-policy: all
            import-policy: all
            peer-as: 100
            afi-safi:
              - afi-safi-name: evpn
                admin-state: enable
              - afi-safi-name: ipv4-unicast
                admin-state: disable
            local-as:
              as-number: 100
            timers:
              minimum-advertisement-interval: 1
        neighbor:
          - peer-address: 10.0.0.1
            admin-state: enable
            peer-group: iBGP-overlay
            transport:
              local-address: 10.0.0.2
          - peer-address: 192.168.12.2
            peer-group: eBGP-underlay
  - name: l3vrf-1
    type: ip-vrf
    admin-state: enable
    interface:
      - name: irb1.0
    vxlan-interface:
      - name: vxlan1.10000
    protocols:
      bgp-evpn:
        bgp-instance:
          - id: 1
            admin-state: enable
            vxlan-interface: vxlan1.10000
            evi: 10000
      bgp-vpn:
        bgp-instance:
          - id: 1
            route-target:
              export-rt: target:1:10000
              import-rt: target:1:10000
  - name: vrf-1
    type: mac-vrf
    admin-state: enable
    interface:
      - name: ethernet-1/1.0
      - name: irb1.0
    vxlan-interface:
      - name: vxlan1.1
    protocols:
      bgp-evpn:
        bgp-instance:
          - id: 1
            admin-state: enable
            vxlan-interface: vxlan1.1
            evi: 1
      bgp-vpn:
        bgp-instance:
          - id: 1
            route-target:
              export-rt: target:1:1
              import-rt: target:1:1
